CREATE TABLE pedidos (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    CLIENTE_ID BIGINT NOT NULL,
    DATA DATE NOT NULL,
    VALOR_TOTAL DECIMAL(10, 2) NOT NULL,
    CONSTRAINT FK_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES clientes(ID)
)ENGINE=INNODB;